apiVersion: v1
kind: Service
metadata:
  annotations:
    autoportforward/tcp1234.usenodeport: "true"
  labels:
    service.kubernetes.io/autoportforward: "true"
  name: apf-test
  namespace: apf-test
spec:
  ports:
  - name: tcp1234
    port: 1234
    protocol: TCP
    targetPort: 1234
  - name: tcp1235
    port: 1235
    protocol: TCP
    targetPort: 1235
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
