apiVersion: v1
kind: Service
metadata:
  labels:
    service.kubernetes.io/autoportforward: "true"
  name: apf-test
  namespace: apf-test
spec:
  ports:
  - name: tcp1234
    port: 1234
    protocol: TCP
    targetPort: 1234
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
