apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoportforward-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: autoportforward
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: autoportforward-cluster-role
  apiGroup: rbac.authorization.k8s.io
