apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoportforward-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: autoportforward-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: autoportforward-server
    spec: 
      serviceAccountName: autoportforward
      containers:
      - name: server
        image: ghcr.io/inglemr/asusautoportforward:{{.Values.autoportforward.version}}
        imagePullPolicy: Always
        ports:        
        - name: http
          containerPort: 8080
          protocol: TCP   
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        {{- with .Values.autoportforward.resources}}
        resources:
          {{- toYaml .| nindent 8 }}
        {{- end }}
        env:
        - name: ROUTER_ADDRESS
          value: {{ .Values.autoportforward.config.router_address }}
        - name: ROUTER_USERNAME
          value: {{ .Values.autoportforward.config.router_username }}
        - name: ROUTER_PASSWORD
          value: {{ .Values.autoportforward.config.router_password }}