apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoportforward-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: autoportforward-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: autoportforward-server
    spec: 
      containers:
      - name: server
        image: inglemr/autoportforward:{{.Values.autoportforward.version}}
        imagePullPolicy: Always
        serviceAccountName: autoportforward
        ports:        
        - name: http
          containerPort: 8080
          protocol: TCP   
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{- with .Values.autoportforward.resources}}
        resources:
          {{- toYaml .| nindent 8 }}
        {{- end }}
        env:
          {{- range $env_name, $env := .Values.autoportforward.env }}
          - name: {{ $env_name }}
            value: "{{ $env }}"
          {{- end }}
